version: '3.8'

services:
  apache-php:
    image: zanryu/gamingcommunity-apache-php:latest
    container_name: apache-php
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html/gameCommunity/backend
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: game_community
      MYSQL_USER: pablo
      MYSQL_PASSWORD: 12345678
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - mysql

  angular:
    image: zanryu/gamingcommunity-angular:latest
    container_name: angular
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    command: ["npm", "start"]

volumes:
  mysql-data:
